version: '3.8'

services:
  concert-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - API_ENDPOINT=${API_ENDPOINT:-http://localhost:3000}
      - NODE_ENV=production
    restart: unless-stopped
